### ISSUE TITLE
Failed to launch after v2.16.0 update, 'xlib' distribution was not found 

### ISSUE THREAD

**Issue by KrisAphalon** [thenaterhood/gscreenshot#118]
After updating to v2.16.0 version, gscreenshot refuses to work.
I tried running it with and without xlib installed, both times the same message appeared.

Traceback after running `gscreenshot` command
```
Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 33, in <module>
    sys.exit(load_entry_point('gscreenshot==2.16.0', 'gui_scripts', 'gscreenshot')())
  File "/usr/bin/gscreenshot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/gscreenshot/__init__.py", line 23, in <module>
    from pkg_resources import resource_string, require, resource_filename
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xlib' distribution was not found and is required by gscreenshot
```

`uname -a`:
```
Linux aphalon 5.13.0-1-MANJARO #1 SMP PREEMPT Mon Jun 7 06:16:10 UTC 2021 x86_64 GNU/Linux
```

`pacman -Q | grep xlib`:
```
python-xlib 0.30-1
```

`pacman -Q | grep gscreenshot`:
```
gscreenshot 2.16.0-1
```

`pacman -Q | grep python`:
[python.txt](https://github.com/thenaterhood/gscreenshot/files/6727978/python.txt)

**Comment by thenaterhood** [comment]
Well that's no bueno. Let me see if I can find an answer.

**Comment by KrisAphalon** [comment]
I can say that v2.16.1 indeed fixed the issue

**Comment by thenaterhood** [comment]
You're quick! I was just typing that v2.16.1 should fix it. Great to hear!
