### ISSUE TITLE
Package not found on python 3.10

### ISSUE THREAD

**Issue by AckslD** [thenaterhood/gscreenshot#126]
After upgrading to python 3.10 on arch linux `gscreenshot` doesn't seem to work anymore and gives the error:
```
Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 33, in <module>
    sys.exit(load_entry_point('gscreenshot==2.17.0', 'gui_scripts', 'gscreenshot')())
  File "/usr/bin/gscreenshot", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gscreenshot
```
when calling it. I've installed `gscreenshot` using `yay -S gscreenshot` and also tried to reinstall but still get the same error.

**Comment by AckslD** [comment]
Sorry, just forgot to clean build, after that it works
