### ISSUE TITLE
2.5.0 doesn't start

### ISSUE THREAD

**Issue by pavroo** [thenaterhood/gscreenshot#15]
Hi
Just built 2.5.0 on Debian testing.
It doesn't launch, and here is the output:

Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 9, in <module>
    load_entry_point('gscreenshot==2.5.0', 'gui_scripts', 'gscreenshot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/gscreenshot/__init__.py", line 18, in <module>
    from gscreenshot.screenshooter.scrot import Scrot
ImportError: No module named screenshooter.scrot

**Comment by thenaterhood** [comment]
Damn those sneaky `__init__.py` files! Missed one on commit, but this should fix it.

https://github.com/thenaterhood/gscreenshot/releases/tag/v2.5.1
