### ISSUE TITLE
can't take screenshots after python update

### ISSUE THREAD

**Issue by razzat008** [thenaterhood/gscreenshot#170]
Everything was working perfectly fine until my system ran through an update.
The update included many python libraries or smth, linux kernel.

```bash
> gscreenshot

Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 33, in <module>
    sys.exit(load_entry_point('gscreenshot==3.4.0', 'gui_scripts', 'gscreenshot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/gscreenshot", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gscreenshot
```

Python version:
`Python 3.11.3`

GNU/Linux:
`6.3.1-arch1-1`

**Comment by thenaterhood** [comment]
You may need to just rebuild gscreenshot (if you use the AUR, do a clean build without the cache)

**Comment by razzat008** [comment]
Yes, that worked! Thanks a lot!
