### ISSUE TITLE
crash in launch

### ISSUE THREAD

**Issue by stef204** [thenaterhood/gscreenshot#36]
gscreenshot 2.5.6-1
python 3.5.2
linux 4.8.8

% `gscreenshot`
```

Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 11, in <module>
    load_entry_point('gscreenshot==2.5.6', 'gui_scripts', 'gscreenshot')()
  File "/usr/lib/python3.5/site-packages/gscreenshot/frontend/gtk.py", line 238, in main
    builder,
  File "/usr/lib/python3.5/site-packages/gscreenshot/frontend/gtk.py", line 27, in __init__
    self._app.screenshot_full_display()
  File "/usr/lib/python3.5/site-packages/gscreenshot/__init__.py", line 49, in screenshot_full_display
    self.screenshooter.grab_fullscreen(delay)
  File "/usr/lib/python3.5/site-packages/gscreenshot/screenshooter/scrot.py", line 34, in grab_fullscreen
    self._call_scrot(['-d', str(delay)])
  File "/usr/lib/python3.5/site-packages/gscreenshot/screenshooter/scrot.py", line 83, in _call_scrot
    self._image = Image.open(self.tempfile)
AttributeError: module 'PIL.Image' has no attribute 'open'
```

**Comment by thenaterhood** [comment]
Uh oh!

Could you verify that you have PIL installed, and what version it is? It'll likely have been installed by your package manager; on mine, the package is python-pillow. You can also check via pip, where the name will be "Pillow". If you don't have it installed and you've installed gscreenshot with `python setup.py install` then I likely made a packaging error.

I _suspect_ that there's a packaging error on my end. You may be able to get around this by manually installing pillow for your system, through either `pip install pillow` or through your distro's package manager.

**Comment by thenaterhood** [comment]
Here's something for you to try:

Rather than trying to install using `python setup.py install`, use `pip install -e .`. I may be misinformed regarding how setuptools handles dependencies. Apparently calling the setup script directly does not handle dependencies, while PIP does.

**Comment by stef204** [comment]
I have python-pillow 3.4.2.
I should tell you that I have been using gscreenshot for many months now without a hitch; this problem started fairly recently, probably 2.5.5 or more likely 2.5.6.

**Comment by thenaterhood** [comment]
Very strange. Take this version out for a spin and see if it gets you any further: https://github.com/thenaterhood/gscreenshot/archive/issue-36.zip

To install it, unzip it somewhere, navigate into it until you see the setup.py, and run `sudo python setup.py install`.

**Comment by thenaterhood** [comment]
@stef204 have you had a chance to see if the version linked in the previous comment fixes your issue?

**Comment by stef204** [comment]
sorry, not yet.  will try to do it today. thanks.

**Comment by stef204** [comment]
still crashing:

 ```
% gscreenshot 
Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 11, in <module>
    load_entry_point('gscreenshot==2.5.7', 'gui_scripts', 'gscreenshot')()
  File "/usr/lib/python3.5/site-packages/gscreenshot/frontend/gtk.py", line 238, in main
    builder,
  File "/usr/lib/python3.5/site-packages/gscreenshot/frontend/gtk.py", line 27, in __init__
    self._app.screenshot_full_display()
  File "/usr/lib/python3.5/site-packages/gscreenshot/__init__.py", line 49, in screenshot_full_display
    self.screenshooter.grab_fullscreen(delay)
  File "/usr/lib/python3.5/site-packages/gscreenshot/screenshooter/scrot.py", line 34, in grab_fullscreen
    self._call_scrot(['-d', str(delay)])
  File "/usr/lib/python3.5/site-packages/gscreenshot/screenshooter/scrot.py", line 83, in _call_scrot
    self._image = PIL.Image.open(self.tempfile)
AttributeError: module 'PIL.Image' has no attribute 'open'
```

`

**Comment by thenaterhood** [comment]
Try reinstalling your python-pillow packages. I have no idea what could be going on on the gscreenshot side, as nothing regarding that logic has changed in the past few versions. I'm not able to replicate this myself either.

**Comment by stef204** [comment]
OK, let me look at all the dependencies and reinstall them.  Will post again soon.

**Comment by stef204** [comment]
We are good to go!  Just reinstalled python-pillow with `--force` and all is well, we are back!!
I should have come up with that on my own.  Sorry.
I know I've already said it but let me say it again: great job on gscreenshot!

**Comment by thenaterhood** [comment]
No worries! Sometimes that's just how things end up going. Glad you like gscreenshot!
