### ISSUE TITLE
2.7.1 failed

### ISSUE THREAD

**Issue by pavroo** [thenaterhood/gscreenshot#59]
Hi
The new build of 2.7.1 went fine (on Debian testing Stretch), but doesn't work using "Selection" and "Window" options.
Slop is in the latest version of 6.3.38
The output:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gscreenshot/frontend/gtk.py", line 77, in on_button_selectarea_clicked
    self._button_select_area_or_window_clicked(args)
  File "/usr/lib/python2.7/dist-packages/gscreenshot/frontend/gtk.py", line 82, in _button_select_area_or_window_clicked
    self._app.screenshot_selected
  File "/usr/lib/python2.7/dist-packages/gscreenshot/frontend/gtk.py", line 42, in take_screenshot
    screenshot = app_method(self._delay)
  File "/usr/lib/python2.7/dist-packages/gscreenshot/__init__.py", line 72, in screenshot_selected
    self.screenshooter.grab_selection(delay)
  File "/usr/lib/python2.7/dist-packages/gscreenshot/screenshooter/__init__.py", line 55, in grab_selection
    crop_box = self.selector.region_select()
  File "/usr/lib/python2.7/dist-packages/gscreenshot/selector/slop.py", line 27, in region_select
    return self._get_boundary_interactive()
  File "/usr/lib/python2.7/dist-packages/gscreenshot/selector/slop.py", line 73, in _get_boundary_interactive
    slop_parsed[spl[0]] = spl[1]
IndexError: list index out of range

**Comment by thenaterhood** [comment]
Huh, look at that. This may have been uncovered by another bug that was fixed in 2.7.1. I haven't seen this, but I appear to be lagging behind a version on slop, so I'll take a look.

**Comment by thenaterhood** [comment]
Could you do me a big favor, and let me know what the output of this command is?

`slop --nodecorations=0 -f "X=%x,Y=%y,W=%w,H=%h"`

**Comment by pavroo** [comment]
slop --nodecorations=0 -f "X=%x,Y=%y,W=%w,H=%h"

Failed to detect a compositor, OpenGL hardware-accelleration disabled...
X=339,Y=373,W=629,H=416

**Comment by thenaterhood** [comment]
Thank you!

I think I see what it is, I'm betting that extra line is breaking some parsing. I'll try to have a fix this weekend, likely v2.7.2.

**Comment by thenaterhood** [comment]
I've released v2.7.2 (https://github.com/thenaterhood/gscreenshot/releases/tag/v2.7.2), which should fix this. Let me know if you have further problems.

**Comment by pavroo** [comment]
all fine, thank's.
