### ISSUE TITLE
2.9.0 issue

### ISSUE THREAD

**Issue by pavroo** [thenaterhood/gscreenshot#66]
Hi
The latest build 2.9.0 on Debian testing went fine, but cant run it.
The output:
`Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 11, in <module>
    load_entry_point('gscreenshot==2.9.0', 'gui_scripts', 'gscreenshot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/gscreenshot/__init__.py", line 23, in <module>
    from gscreenshot.screenshooter.factory import ScreenshooterFactory
  File "/usr/lib/python2.7/dist-packages/gscreenshot/screenshooter/factory.py", line 4, in <module>
    from gscreenshot.screenshooter.exceptions import NoSupportedScreenshooterError
ImportError: No module named exceptions
`
Python 2.7.13 and 3.5.3 is installed.

**Comment by thenaterhood** [comment]
My apologies! 2.9.1 should fix that. I goofed.
