### ISSUE TITLE
The 'pygobject' distribution was not found and is required by gscreenshot

### ISSUE THREAD

**Issue by Iambecomeroot** [thenaterhood/gscreenshot#68]
After a recent `pacaur -Suy` every tme I run `gscreenshot` I get the following error:
```
Traceback (most recent call last):
  File "/usr/sbin/gscreenshot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pygobject' distribution was not found and is required by gscreenshot
```

I have reproduced this on two computers so I am assuming it's not me. I have also tried installing the package with `pip` and `pacman`.

Since `gscreenshot -v` isn't working here's `pacaur -Q | grep gscreenshot`:
```
gscreenshot 2.9.1-1
```

`pacaur -Q | grep object`:
```
gobject-introspection 1.54.1-1
gobject-introspection-runtime 1.54.1-1
pygobject-devel 3.26.0-1
pygobject2-devel 2.28.6-13
python-gobject 3.26.0-1
python2-gobject 3.26.0-1
python2-gobject2 2.28.6-13
```

`uname -a`:
```
Linux Hermes 4.13.4-1-ARCH #1 SMP PREEMPT Thu Sep 28 08:39:52 CEST 2017 x86_64 GNU/Linux
```

**Comment by thenaterhood** [comment]
What's your full Python version? I see 3.6, but I'm wondering the patch version.

I haven't had any packagers report a problem and I haven't encountered it on any systems myself. There haven't been any changes around pygobject or the build scripts in this release, other than the gscreenshot version number.

**Comment by Iambecomeroot** [comment]
Python is `3.6.2-1`. I have this problem on 2 computers. Is it possible that some package I have on both of them is messing with pygobject?

Anyway, here is `pacuar -Q | grep python`:
```
mysql-python 1.2.5-1
python 3.6.2-1
python-acme 0.19.0-1
python-appdirs 1.4.3-1
python-asn1crypto 0.23.0-1
python-beaker 1.8.1-2
python-cairo 1.13.3-1
python-cffi 1.10.0-1
python-chardet 3.0.4-1
python-colorama 0.3.9-1
python-configargparse 0.12.0-1
python-configobj 5.0.6-3
python-cryptography 2.0.3-1
python-dbus 1.2.4-2
python-dbus-common 1.2.4-2
python-decorator 4.1.2-1
python-distutils-extra 2.39-2
python-future 0.16.0-2
python-gobject 3.26.0-1
python-idna 2.6-1
python-mako 1.0.7-1
python-markupsafe 1.0-1
python-mock 2.0.0-2
python-olefile 0.44-1
python-packaging 16.8-2
python-parsedatetime 2.4-1
python-pbr 3.1.1-1
python-pexpect 4.2.1-2
python-pillow 4.3.0-1
python-pip 9.0.1-2
python-ply 3.10-1
python-psutil 5.3.1-1
python-ptyprocess 0.5.2-1
python-pycparser 2.18-1
python-pycups 1.9.73-3
python-pycurl 7.43.0-3
python-pyopenssl 17.3.0-1
python-pyparsing 2.2.0-1
python-pyrfc3339 1.0-2
python-pyside-common 1.2.4-6
python-pyte 0.6.0-1
python-pytz 2017.2-1
python-pywal 0.6.9-1
python-requests 2.18.4-1
python-setuptools 1:36.5.0-1
python-six 1.11.0-1
python-urllib3 1.22-1
python-wcwidth 0.1.7-2
python-werkzeug 0.12.2-1
python-xdg 0.25-4
python-xlib 0.20-1
python-zope-component 4.4.1-1
python-zope-event 4.3.0-1
python-zope-interface 4.4.3-1
python2 2.7.14-1
python2-acme 0.19.0-1
python2-appdirs 1.4.3-1
python2-arrow 0.10.0-1
python2-asn1crypto 0.23.0-1
python2-babel 2.5.1-1
python2-backports 1.0-1
python2-backports.functools_lru_cache 1.4-2
python2-bcrypt 3.1.3-1
python2-bottle 0.12.13-1
python2-cairo 1.13.3-1
python2-cffi 1.10.0-1
python2-chardet 3.0.4-1
python2-click-5.1 5.1-2
python2-colorama 0.3.9-1
python2-configargparse 0.12.0-1
python2-configobj 5.0.6-3
python2-cryptography 2.0.3-1
python2-cycler 0.10.0-2
python2-dateutil 2.6.1-1
python2-dbus 1.2.4-2
python2-distutils-extra 2.39-2
python2-docutils 0.14-1
python2-enum34 1.1.6-1
python2-funcsigs 1.0.2-1
python2-future 0.16.0-2
python2-gobject 3.26.0-1
python2-gobject2 2.28.6-13
python2-idna 2.6-1
python2-imagesize 0.7.1-2
python2-ipaddress 1.0.18-1
python2-jinja 2.9.6-1
python2-lockfile 0.12.2-2
python2-markupsafe 1.0-1
python2-matplotlib 2.0.2-1
python2-mock 2.0.0-2
python2-ndg-httpsclient 0.4.3-1
python2-nose 1.3.7-3
python2-numpy 1.13.3-1
python2-olefile 0.44-1
python2-packaging 16.8-2
python2-parsedatetime 2.4-1
python2-pbr 3.1.1-1
python2-pillow 4.3.0-1
python2-pip 9.0.1-2
python2-pivy 20101207-2
python2-ply 3.10-1
python2-psutil 5.3.1-1
python2-pyasn1 0.3.6-1
python2-pycparser 2.18-1
python2-pygments 2.2.0-1
python2-pyinotify 0.9.6-3
python2-pyopenssl 17.3.0-1
python2-pyparsing 2.2.0-1
python2-pyqt5 5.9-1
python2-pyrfc3339 1.0-2
python2-pyserial 3.4-1
python2-pyside 1.2.4-6
python2-pyside-tools 0.2.15-4
python2-pythondialog 3.4.0-1
python2-pytz 2017.2-1
python2-requests 2.18.4-1
python2-semantic-version 2.6.0-1
python2-setuptools 1:36.5.0-1
python2-shiboken 1.2.4-3
python2-sip 4.19.3-1
python2-six 1.11.0-1
python2-snowballstemmer 1.2.1-2
python2-sphinx 1.6.4-1
python2-sphinx-alabaster-theme 0.7.10-1
python2-sphinx_rtd_theme 0.2.4-1
python2-sphinxcontrib-websupport 1.0.1-1
python2-sqlalchemy 1.1.14-1
python2-typing 3.6.1-1
python2-urllib3 1.22-1
python2-urwid 1.3.1-3
python2-werkzeug 0.12.2-1
python2-whoosh 2.7.4-2
python2-zope-component 4.4.1-1
python2-zope-event 4.3.0-1
python2-zope-interface 4.4.3-1
```

**Comment by thenaterhood** [comment]
I think I've found the problem! At some point in the very recent past, pygobject has changed and it should be correctly referenced in my `setup.py` as `gi`.

Once I've confirmed that works across the versions I expect it to, I'll release a 2.9.2 if appropriate, or I'll patch it in the PKGBUILD for a 2.9.1-2. I'll keep you posted.

**Comment by thenaterhood** [comment]
I've pushed v2.9.2 which as far as I can tell solves the issue. The AUR package is also updated.

If this doesn't take care of things, feel free to re-open the issue and I'll take another look.

**Comment by Iambecomeroot** [comment]
Working! Thanks a bunch! I love gscreenshot btw.
