### ISSUE TITLE
Missing gi module

### ISSUE THREAD

**Issue by pavroo** [thenaterhood/gscreenshot#83]
Hi
The latest version 2.10.0 failed to start on Debian stable Stretch (works fine on testing Buster).
The output:
 `Traceback (most recent call last):
  File "/usr/bin/gscreenshot", line 11, in <module>
    load_entry_point('gscreenshot==2.10.0', 'gui_scripts', 'gscreenshot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/gscreenshot/frontend/gtk.py", line 4, in <module>
    from gi import pygtkcompat
ImportError: No module named gi`
I have python3-gi 3.22.0 installed

**Comment by thenaterhood** [comment]
It looks like (based on that output) there's a mismatch in Python versions. Gscreenshot is running on Python 2.7, while gi for Python 3 is installed. I think pygtk provides gi in this instance as well.

Gscreenshot can run on both Python 2.7 and Python 3, so if Debian has dropped some packages for Python 2.7 feel free to install gscreenshot on Python 3 instead (same process, just swap out the Python binary when you install).

**Comment by pavroo** [comment]
Installing python-gi instead of python3-gi solved the problem, thank's
